---

- name: Enable firewall
  ufw: 
    state: enabled
    policy: deny

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS
  ufw: 
    rule: allow
    port: 443
    proto: tcp

- name: Allow SSH
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow 4000
  ufw:
    rule: allow
    port: 4000
    proto: tcp